### ISSUE TITLE
Source code dummy devices

### ISSUE THREAD

**Issue by tstorek** [FIWARE/tutorials.IoT-Sensors#10]
Hello,

I'd like to know if there is any possibility to view the code for the dummy devices? 
I'd like to use it as workflow inspiration for my own devices.

Thanks,

**Comment by jason-fox** [comment]
The dummy devices are a simple Node JS application, all the source code can be found in the *tutorials.Step-by-Step*  repository.

* https://github.com/FIWARE/tutorials.Step-by-Step/tree/master/context-provider/controllers/iot
* https://github.com/FIWARE/tutorials.Step-by-Step/blob/master/context-provider/models/devices.js
*  https://github.com/FIWARE/tutorials.Step-by-Step/blob/master/context-provider/models/command/ultralight.js
* https://github.com/FIWARE/tutorials.Step-by-Step/blob/master/context-provider/models/measure/ultralight.js

**Comment by tstorek** [comment]
Thank you very much, I was simply looking in the wrong repo :)
