### ISSUE TITLE
Few of the environment variables are missing

### ISSUE THREAD

**Issue by ksasan** [FIWARE/tutorials.IoT-Sensors#12]
I was just exploring the tutorial for WiFi, when found that few of environment settings required for docker-compose yaml file are missing:

Below lines may be saved as file env.sh and run/setup (before running ./service start) using ". env.sh" command

```
export DEBUG=tutorial:*
export WEB_APP_PORT=3000
export IOTA_HTTP_HOST=iot-agent
export IOTA_HTTP_PORT=7896
export DUMMY_DEVICES_PORT=3001
export DUMMY_DEVICES_API_KEY=4jggokgpepnvsb2uv4s40d59ov
export IOTA_SOUTH_PORT=3002
export MONGO_DB_VERSION=3.6
export MONGO_DB_PORT=27017
export ORION_VESION=latest
export ORION_PORT=1026
```

**Comment by cxzero** [comment]
Just to notice, I see now the environmental variables defined either on _.env_ file or under "environment" key on "tutorial" service in _docker-compose.yml_ file. Perhaps there were some changes made in the mid-time.

**Comment by jason-fox** [comment]
`docker-compose` updated. Closing as Fixed
