### ISSUE TITLE
cant start services

### ISSUE THREAD

**Issue by mohamed-hatem** [FIWARE/tutorials.IoT-Sensors#8]
whenever i try to start the services from cygwin using the ./services create command i get these message errors :
./services: line 7: $'\r': command not found
: invalid option 8: set: -
set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]
./services: line 9: $'\r': command not found
./services: line 10: syntax error near unexpected token `$'{\r''
'/services: line 10: `loadData () {

is there a way to fix them?

**Comment by jason-fox** [comment]
It looks like the file has gained windows style line endings somehow.

You'll need to convert it back to Unix style line endings using `dos2unix services` to get the script to run

See the answers to this  [Unix Stack Exchange Question](https://unix.stackexchange.com/questions/391223/why-am-i-getting-line-1-r-command-not-found) for more options.
